name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
    - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Install dotnet 6"
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Test the project
      run: dotnet test ./src/HelloWorld.sln --configuration Release --output ./drop

    - name: Publish the project
      run: dotnet publish ./src/HelloWorld/HelloWorld.csproj --configuration Release --output ./drop
  
    - name: Publish release as artifect
      uses: actions/upload-artifact@v2
      with:
        name: function
        path: drop

  release:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_NAME: func6
    steps:
    - name: Download function Build
      uses: actions/download-artifact@v2
      with:
        name: function
        path: ./function
    - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './function'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}