name: .NET

on:
 # Configureer triggers voor een push op de main branch
 # Configureer triggers voor een pull request
  pull_request:
    branches:    
    - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Install dotnet 6"
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Build and Test a project
      run: dotnet publish ./src/HelloWorld/HellowWorld.csproj --configuration Release --output ./drop
  
