name: .NET

on:
 # Configureer triggers voor een push op de main branch
 # Configureer triggers voor een pull request
 pull_request:
  branches:    
  - main
 # Configureer een trigger voor een handmatige build
 workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WORKDIR: "TODO"
      CONFIG: "TODO"
      AZURE_FUNCTIONAPP_NAME: "func6"
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2


    - name: Build and Test a project
      run: dotnet publish ./src/HelloWorld/HellowWorld.csproj --configuration Release --output ./drop
  
